public DateInterval diff ( DateTimeInterface $datetime2 [, bool $absolute = FALSE ] )
public string format ( string $format )
public int getOffset ( void )
public int getTimestamp ( void )
public DateTimeZone getTimezone ( void )